### ISSUE TITLE
[Proposal] Use `ng-packagr` as packager

### ISSUE THREAD

**Issue by JimiC** [mpx200/ng-dygraphs#20]
In light of issue #18, I would like to propose to switch to using [ng-packagr](https://github.com/dherges/ng-packagr) as the packager of this `NgModule`.

**Advantages**
 - It produces `es5` compatible code.
 - It produces `es6` compatible code.
 - It produces `umd` bundle code.
 - Produces code that works out of the box with both `ts` and `js` `angular` projects

**Disadvantages**
 - Requires to read the manual (RTFM)

A good tutorial on how to use it can be found [here](https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e).

You can see it in action @ <https://github.com/JimiC/ng-dygraphs/tree/ng-packagr>.

@mpx200 Thoughts?

**Comment by JimiC** [comment]
Just an added info, in case you adopt `ng-packagr`, is that when publishing you will have to do it via `npm publish dist` as only the dist folder needs to be published.

**Comment by JimiC** [comment]
@mpx200 I was trying to determine which `@angular/cli` has `v4.2.5` as dependencies and I found the following:

- `@angular/cli v1.4.9` comes with `v4.2.4`
- `@angular/cli v1.5.0` comes with `v5.0.0`

As we are going to switch to `ng-packagr` we will introduce breaking changes, so a minor version release (`0.4.0`) is prudent. So the question is, while we are at it, should we move to `@angular/cli v1.5.0` or go directly to `v1.6.1` which was released some hours ago, or even better support the last stable version of the previous version (which is `v1.5.5`)?

**Comment by mpx200** [comment]
go directly to 1.6.1, just please notify me when i can do publish
