### ISSUE TITLE
TS2346: Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by bushev** [mpx200/ng-dygraphs#7]
Hello! I faced with a compilation error. It seems that module is a slightly out of date.

**TS2346: Supplied parameters do not match any signature of call target.**

![image](https://cloud.githubusercontent.com/assets/7535766/25859700/0a3fabbe-34e8-11e7-8e82-70775cda50dc.png)

**Comment by mpx200** [comment]
tnx man for the effort
